apiVersion: v1
kind: Pod
metadata:
  name: check-scheduler2
spec:
  schedulerName: storage-capacity-prioritization-scheduler
  containers:
  - name: container1
    image: k8s.gcr.io/pause:2.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
