apiVersion: v1
kind: Pod
metadata:
  name: pvc1-pod
spec:
  schedulerName: storage-capacity-prioritization-scheduler
  containers:
  - image: alpine
    name: alpine
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: claim-volume
      mountPath: /data
  volumes:
  - name: claim-volume
    persistentVolumeClaim:
      claimName: pvc1
