apiVersion:  kind.x-k8s.io/v1alpha4
kind: Cluster
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: "kubeadm.k8s.io/v1beta2"
  kind: ClusterConfiguration
  metadata:
    name: config
  kubernetesVersion: "v@KUBERNETES_VERSION@"
  networking:
    serviceSubnet: 10.0.0.0/16
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane
# the three workers
- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
    - containerPath: /tmp/scp-scheduler
      hostPath: /tmp/scp-scheduler/lvmd1
- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
    - containerPath: /tmp/scp-scheduler
      hostPath: /tmp/scp-scheduler/lvmd2
- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
    - containerPath: /tmp/scp-scheduler
      hostPath: /tmp/scp-scheduler/lvmd3
