apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "storage-capacity-prioritization-scheduler.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "storage-capacity-prioritization-scheduler.labels" . | nindent 4 }}
